### ISSUE TITLE
omnisharp.json ignored by VS Code?

### ISSUE THREAD

**Issue by dluc** [OmniSharp/omnisharp-roslyn#1183]
I placed a copy of omnisharp.json in the root of a C# solution, but regardless of the changes made, when I format the document in VS Code, these settings are ignored.

Instructions used: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

I opened also this issue, in case this is the wrong repo:
https://github.com/OmniSharp/omnisharp-vscode/issues/2283

**Comment by filipw** [comment]
Can you provide a repro project? It certainly should work, I just double checked again.

Looking at your error description in the other issue, something else seems wrong though (i.e. OmniSharp is not running at all) because the format you expect is the **default** OmniSharp code format so it would get applied on code formatting action even without `omnisharp.json` in place.

**Comment by dluc** [comment]
fixed - see https://github.com/OmniSharp/omnisharp-vscode/issues/2283

Thanks
