### ISSUE TITLE
Provide options to control MSBuild discovery and selection

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#1186]

**Comment by Pilchie** [comment]
@rchande Note - I think this will be important for .NET Core 3, given that the VS 2017 MSBuild is marked as incompatible with .NET Core 3. For me, with both VS 2017 and 2019 installed, Omnisharp always picks the 2017 instance, even if I start from a 2019 command prompt :(

**Comment by rainersigwald** [comment]
The command prompt problem should be fixed by #1347.

Tactically, it might also be good to do some sorting in `VisualStudioInstanceProvider`. Maybe just by version descending, though it might also be nice to work in prerelease/not somehow--but that probably just takes you back to configuration. On my machine I'd want prerelease highest always, but that's because I work on VS and any released version of VS I have installed is an emergency backup/repro environment.

**Comment by Pilchie** [comment]
And #1347 should be in the next release already.

**Comment by peter-vanpoucke** [comment]
Any progress on this? Because it seems only [this workaround](https://github.com/OmniSharp/omnisharp-roslyn/issues/1094#issuecomment-405414145) can fix this...

**Comment by JohnGalt1717** [comment]
Same here. It's insisting on selecting VS.net 2019 Preview msbuild and then doesn't suggest anything as a result.

**Comment by filipw** [comment]
This was implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/1545#issuecomment-510461836
