### ISSUE TITLE
Formatting Options, private/internal keyword formatting

### ISSUE THREAD

**Issue by SlowLogicBoy** [OmniSharp/omnisharp-roslyn#1242]
Are there settings for private/internal keyword formatting?
Something like:
```json
"PrivateMethodKeyword": "Leave", //Leaves private keyword as is for methods (ether specified or not)
"PrivateFieldKeyword": "Remove", //Removes private keyword if it's specified for fields
"InternalClassKeyword": "Add", //Adds internal keyword if doesn't exist before class
```
I was unable to find anything similar to this in [Here](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options)

**Comment by filipw** [comment]
This is not possible at the moment via the formatter - it only deals with code formatting (indentation, new lines, spacing, wrapper and so on) rather than code simplification. 

The closest you could get to something similar (although that is a bit of stretch) is to install [Roslynator Refactorings](https://github.com/JosefPihrt/Roslynator/blob/master/src/Refactorings/README.md) and use it to help you manually change accessibility.

**Comment by ExceptionGit** [comment]
@DustinCampbell 
Can you're tell when? https://github.com/OmniSharp/omnisharp-vscode/issues/1726 ~2 year ago
