### ISSUE TITLE
Why Omnisharp Roslyn isn't .NET Core base on OSX/Linux ?

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [OmniSharp/omnisharp-roslyn#1384]
You said in the readme:

> OmniSharp-Roslyn is built with the **.NET Core SDK on Windows** and **Mono on OSX/Linux**. It targets the net461 target framework. OmniSharp requires mono (>=5.2.0) if it is run on a platform other than Windows. 

So the question is that why we don't use .NET Core for OSX/Linux platform? I think it's cloud be better and we'll have .NET Core advantages instead mono. I there any plan for this?

Also here we have an image that shows even OmniSharp for Windows is .net framework.
![code---insiders_2018-10-07_22-04-04](https://user-images.githubusercontent.com/22220356/51203677-e399e780-1916-11e9-82ce-d06f6b358bac.png)

**Comment by filipw** [comment]
This is by design, and is needed to in order to use MSBuild tasks targeting Full Framework - as they don't work on CoreCLR. Note that OmniSharp ships with its own embedded mono runtime too, so it can run even if you don't have a global mono installed. In other words, a full framework based OmniSharp can support all kinds of projects (full framework, .net core, unity etc) but a .net core based OmniSharp has a lot of troubles supporting non-.NET Core projects. We used to build .NET Core OmniSharp in the past but we went away from it.

You can find more information here https://github.com/OmniSharp/omnisharp-roslyn/pull/988 and here https://github.com/OmniSharp/omnisharp-roslyn/issues/666 and here https://github.com/OmniSharp/omnisharp-roslyn/pull/915
