### ISSUE TITLE
No support for 'preview' language versions?

### ISSUE THREAD

**Issue by FiniteReality** [OmniSharp/omnisharp-roslyn#1487]
I'm writing some code to try out the new 'unmanaged constructed types' and 'static local functions' features, and as expected OmniSharp is flagging this up with error CS8652, stating that the feature is not supported and currently in preview.

However, the error says to use the `preview` language version to use these features, and upon specifying this in the `LangVersion` property, these errors remain. To hide these errors, I had to specify `8.0` as the value, instead of what the error had specified.

I believe this is due to this switch not including `preview` as a possible value, though I may be wrong since I'm not familiar with the code:
https://github.com/OmniSharp/omnisharp-roslyn/blob/46c814a74c0dae8f4c2541bff7c65f686597af04/src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs#L38-L53

**Comment by FiniteReality** [comment]
I don't think there'll be any breaking changes if that entire snippet was replaced with [LanguageVersion.TryParse](https://github.com/dotnet/roslyn/blob/3212a11465fab829b4ba570a28a7a939a927fb9a/src/Compilers/CSharp/Portable/LanguageVersion.cs#L263), so that could be a possible fix ensuring that this won't happen again in the future.

**Comment by filipw** [comment]
You are right, the `Preview` value is missing (as well as another new value `LatestMajor`) - both came in Roslyn 3.0 and we managed to miss them, thanks for opening the issue.

The reason why the built-in Roslyn language version parser was not used in the first place is because when the project parsing code was originally added, the `LanguageVersion.TryParse` (or its old version `LanguageVersionFacts.TryParse`) API didn't exist yet - it only came in Roslyn 2.1.

**Comment by FiniteReality** [comment]
Ah, I had guessed as much. I'm alright to make a PR to fix this then, right? I'll probably replace it with the TryParse method I mentioned, which is indeed under `LanguageVersionFacts`, I had missed the class declaration a few lines above it while browsing the code.

**Comment by filipw** [comment]
sure, please do!
