### ISSUE TITLE
Using .NET Core SDK to build roslyn on OSX / Linux

### ISSUE THREAD

**Issue by ffimnsr** [OmniSharp/omnisharp-roslyn#1489]
You can build using .NET Core SDK on windows, on linux one should use Mono. There is already implementation of .NET Core on linux, why don't we use it?

**Comment by filipw** [comment]
Can you please elaborate on what you are asking for? Would you like omnisharp-roslyn to be built using .NET Core?

**Comment by ffimnsr** [comment]
@filipw yes, most of the distros nowadays does have package of dotnet-core. Is there any way to completely build the omnisharp-roslyn using it like on windows? 

As I know, mono and dotnet-core are two seperate package and can exists whether the other package is not installed.

**Comment by crupest** [comment]
I'm confused about this too. Since dotnet core has been launched for a long time and it is also designed to be cross platform. I see that you have already used dotnet core on Windows. It seems reasonable to use dotnet core on Linux/OS X to get benifit of sharing a common code base. And maybe dotnet core has better performance and develops faster than mono. Do you have any thoughts or plans on this?

**Comment by filipw** [comment]
OmniSharp was a .NET Core app for some time, but we had to switch to full framework.
Have a look here for more context and links to issues explaining the challenges https://github.com/OmniSharp/omnisharp-roslyn/issues/1384#issuecomment-454517526

In short - because of how .NET Core handles assembly resolution, and the fact that MSBuild Tasks can run code themselves, OmniSharp cannot run on .NET Core and support *all* project types (desktop .NET, .NET Core, Unity etc). This is possible when it runs on full framework / Mono though.

I'll close this as duplicate - thanks.

**Comment by crupest** [comment]
Got it, thanks!
