### ISSUE TITLE
<LangVersion>latest</LangVersion> resolves to C# 8

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-roslyn#1604]
It seems the Roslyn analyzers don't respect the version of the C# language that is specified in the .csproj of a project.

I have a simple Asp.net Core (v2.2) application that has in the .csproj:
```
<LangVersion>latest</LangVersion>
```
I'm not using the preview C#8 yet. However, using the Roslyn analyzers in VSCode, I'm seeing messages about "using statements":

`'using' statement can be simplified (IDE0063)`

If I let the analyzer "fix it", it goes from:
```
using (var ms = new MemoryStream()) {
...
}
```

to:
```
using var ms = new MemoryStream();
```

However, when I attempt to build, I get an error saying that is not valid in the version of the language I'm using, and to change to a "preview" version. Which I do not want to do.

**Comment by filipw** [comment]
It does respect it, it's just that OmniSharp us built with a new version of Roslyn in which `latest` means actually C# 8 already. See this Roslyn PR https://github.com/dotnet/roslyn/pull/37074

You would be able to build this from the command if you use .NET Core SDK 3.0 RC1 instead of an older one.
This will align itself again next week when .NET Core 3.0 SDK goes RTM.

**Comment by filipw** [comment]
if you want a workaround, set it to `<LangVersion>7.3</LangVersion>`, since as mentioned `latest` is something that doesn't deterministically resolves across different compiler versions. If you set it to 7.3 you will not get that change suggestion anymore in a "predictable" fashion.
