### ISSUE TITLE
csx support does not handle #load's correctly

### ISSUE THREAD

**Issue by JakeSays** [OmniSharp/omnisharp-roslyn#1829]
For some reason omniscript puts each script file in it's own project which breaks intellisense. The purpose of #load scripts is to make available their contents to the script doing the loading. Using a project per file doesn't seem to be working.

What is the reason for the project per file design?

**Comment by nickspoons** [comment]
Which editor are you using?

**Comment by filipw** [comment]
you need to provide more details - a repro project and some steps on what problem you are experiencing

project per file is orthogonal to loading because #loads are handled via source reference resolvers https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Script/ScriptProjectProvider.cs#L104

**Comment by JakeSays** [comment]
Yeah, I think I was mistaken. It seems to be working as I expected.

Sorry for the trouble.
