### ISSUE TITLE
Decompiler does not work.

### ISSUE THREAD

**Issue by HeebeLee** [OmniSharp/omnisharp-roslyn#1881]
I set it up in VSCode "omnisharp.enableDecompilationSupport" Is true.
I created a new Web API project for. Net core on the MacOS platform, and then I started to try whether decompiling works.
In the end, I still can't see the source code part. The method returned is empty or only "throw null".

<img width="582" alt="1" src="https://user-images.githubusercontent.com/11264289/89861598-cb647a00-dbd8-11ea-8818-b5a88efec9d3.png">
<img width="843" alt="2" src="https://user-images.githubusercontent.com/11264289/89861602-cdc6d400-dbd8-11ea-808b-ff8ca2b5d06b.png">
<img width="841" alt="3" src="https://user-images.githubusercontent.com/11264289/89861616-d4ede200-dbd8-11ea-9a3c-4a19259b783d.png">

**Comment by filipw** [comment]
This is currently a limitation in ILSpy and not a bug in OmniSharp. The ref and implementation assemblies are not resolved automatically, in this case the decompilation happens against Microsoft.AspNetCore.App.Ref instead of the implementation assembly.

You can observe the same behavior in Visual Studio as well. When it is fixed there, we will inherit the fix.

**Comment by 616b2f** [comment]
@filipw can you add a reference to the ILSpy bug you mention here? I tried to search they repo for it but didn't find anything. Just for reference and other people that looking for that feature and may wish to follow.

**Comment by filipw** [comment]
See https://github.com/dotnet/roslyn/issues/24349 for more background.
The limitation is that at design time we operate on reference assemblies instead of implementation assemblies.

**Comment by Winter** [comment]
Sorry to dredge up an old issue but the issue was resolved ~8 months ago in https://github.com/dotnet/roslyn/pull/62406 and opening the project in Visual Studio the feature seems to work quite well. Is it likely we'll ever see a fix in omnisharp or is it too much work to implement?

Thank you for all of your hard work!
