### ISSUE TITLE
why this project need visual studio ?

### ISSUE THREAD

**Issue by John0King** [OmniSharp/omnisharp-roslyn#2011]
before today 2020/11/11 +8:00     ，  this  extension  said it need vs privew 16.8 .  
Don't is only need  .net sdk  and  .net framework target package  (for  net461 TFM)?

**Comment by filipw** [comment]
The stand alone 16.8 that is bundled with Omnisharp is a minimal instance that doesn't contain desktop references or doesn't support Unity development, therefore we always select the instance from Visual Studio if you have it installed on your machine and it's > 16.3. However, if you don't have VS on your machine, then it is not required for Omnisharp (except for the above mentioned desktop .NET development)

The issue is we have to select MSBuild before we know what type of project we are dealing with - MSBuild is required to recognize it.

**Comment by John0King** [comment]
@filipw  sorry that I have poor knowledge of  MSBuild and Roslyn.

> The stand alone 16.8 that is bundled with Omnisharp is a minimal instance that doesn't contain desktop references or doesn't support Unity development

won't the IL assembly is inside sdk/runtime folder ? and  `.Desktop` sdk  the IL and `.props` `.target` is also inside that folder.  Unity I don't know that, but it should have a folder in unity product.

anyway ,  omnisharp always select the vs msbuild when vs is installed , this is  pain for people try preview or newer .net core sdk when people do not want to install preview visual studio version.  

I hope that some idea come in and solve these problem before .net 6 ( or people have to install vs preview again)
