### ISSUE TITLE
Release 1.37.6 is not available in Azure Blob Storage

### ISSUE THREAD

**Issue by stijnherreman** [OmniSharp/omnisharp-roslyn#2073]
When trying to use release 1.37.6 in VS Code with `"omnisharp.path": "1.37.6"`, the download fails:

> Installing OmniSharp Version = 1.37.6...
> Platform: linux, x86_64, name=debian, version=10
> 
> Downloading package 'OmniSharp for Linux (x64), Version = 1.37.6' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.37.6/omnisharp-linux-x64.zip. Error code '404')
> Failed at stage: downloadPackage
> 404

https://roslynomnisharp.blob.core.windows.net/releases?restype=container&comp=list&prefix=1.37.6 only lists pre-releases, the stable release is missing.

Possibly related: https://github.com/OmniSharp/omnisharp-vscode/issues/2834

**Comment by stijnherreman** [comment]
The packages are available now, but the download still fails because the version number is appended to the filename: `<Name>1.37.6/omnisharp-linux-x64-1.37.6.zip</Name>`.
For pre-releases it is not appended: `<Name>1.37.6-beta.30/omnisharp-linux-x64.zip</Name>`

I'm not sure if using stable releases through `"omnisharp.path"` is a supported scenario?

**Comment by filipw** [comment]
The publishing task crashed, it worked after restart.
The naming convention is by design.

With regards to your other question, in C# Extension this is not supported at the moment, but there is nothing preventing adding extra logic to treat stable versions differently when constructing the URLs.

However, in general I wouldn't recommend that because there is often coupling between extension version and OmniSharp version in terms of client-server features. Many features require both parts to be in sync.
