### ISSUE TITLE
Question: DTH support not only for C#

### ISSUE THREAD

**Issue by borgdylan** [OmniSharp/omnisharp-roslyn#213]
Would it be possible to support the DTH stuff irrespective of language? I am asking since getting errors and warnings is achievable using the DNX itself as is done by ```dnu build``` and ```dnu pack```.

**Comment by jrieken** [comment]
yes - DTH is language agnostics but has "C#-happy-path"-defaults. However, we use DTH to expand glob-patterns for source files and nuget-based dependencies to populate a Roslyn workspace. The latter only supports c# and vb. There is talk to take this further so that other languages can be supported too.
