### ISSUE TITLE
Why is mono-6.4.0/msbuild-16.3.0 required?

### ISSUE THREAD

**Issue by nkosi23** [OmniSharp/omnisharp-roslyn#2138]
Why have mono-6.4.0/msbuild-16.3.0 become a hard requirement? I am trying to use Omnisharp on a platform having mono6.8 available, but not having a readily available build of msbuild >= 16.3.0 (the only available version is msbuild15). 

Since the task of upgrading the msbuild port does not appear to be trivial, as an alternative I am trying to assess the impact of patching Omnisharp to remove the hard requirement on msbuild 16.3.0 (and if this would be possible at all).

**Comment by filipw** [comment]
It is not a hard requirement, OmniSharp ships with its own bundled MSBuild as well, however if global Mono is available, it is attempted to be used because it will have reference assemblies for desktop .NET, which the bundled one doesn't.

The reason why lowest version of Mono MSBuild is what it is, is because of requirements in .NET Core - e.g. 3.1 requires MSBuiild 16.3 and 5.0 requires 16.8.

You can disable the discovery of global Mono and global MSBuild by adding an `omnisharp.json` file to the root of your project with the content

```
{
   "msbuild": {
       "useBundledOnly": true
   }
}
```

This will work for loading .NET Core projects, for loading desktop .NET the reference assemblies from global Mono are required so you will need to upgrade global Mono.
