### ISSUE TITLE
Ability to provide alternate code formatters

### ISSUE THREAD

**Issue by shocklateboy92** [OmniSharp/omnisharp-roslyn#2167]
I'm one of the contributors to [CSharpier](https://github.com/belav/csharpier), an opinionated code formatter for C# (inspired by prettier for Js and black for python). I would like to be able configure omnisharp to use that to format code instead of the default roslyn code format.

Firstly, I would like to know if you folks are open to that idea and if such a pull request would be accepted before I start doing any serious work.

Assuming it's a yes, I would like to discuss what the best way of going about that is. It would be ideal if omnisharp could load the format provider from a nuget package referenced by the target project like it does rosyln code analyzers, but I don't understand the internal structure of omnisharp well enough to comment on its feasibility yet.

**Comment by filipw** [comment]
Thanks a lot for opening the issue and your interest in the project.

It is by design that we keep Omnisharp closely aligned with Roslyn and therefore would like to use its formatting capabilities only. We do not plan to take on any other custom external dependencies in that area.

However, most of the editors, including including VS Code allow [contributing code formatters separately](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) which I think could be something of interest to you.

**Comment by shocklateboy92** [comment]
Thanks for your response. What I wanted this functionality most in was `omnisharp-vim` actually.

But I understand your reasoning for staying aligned with Roslyn. I will try my luck in getting a new type of action provider into Rosyln itself, like the code analyzers. :crossed_fingers:
