### ISSUE TITLE
We need to get some documentation on dotnet's readthedocs

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-roslyn#297]
https://dotnet.readthedocs.org/en/latest/development/index.html

Could use some content from us on how to get started using omnisharp and editors.

**Comment by willl** [comment]
@Mpdreamz What sort of topics did you have in mind?

Before anyone starts writing anything, perhaps we should have a discussion on what sorts of things need to be covered?

That section is titled `Developing using .NET Core` (currently with sections for:  VS 2015/VS Code/vim/Sublime and I'm sure we can add in Atom to that), I assume if we were to be contributing anything it would be for the four (including Atom, excluding VS 2015) with very common themes and illustrating how to do the same things in each of the editors? Is that the aim?

If so, what sorts of things?

As an example, the [ASP.NET 5 documentation](http://docs.asp.net) has these areas currently covered that we could obtain some inspiration from:
* [Your First ASP.NET 5 Application on a Mac](http://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html): Which features the aspnet-yeoman generator alongside VS Code. For the Atom editor we can highlight [David Driscoll's Atom Yeoman package](https://github.com/david-driscoll/atom-yeoman) and how it's possible to do _everything_ (like an IDE/VS 2015) from within Atom. From creating the app, running tests etc etc.
* [Creating a Cross-Platform Console App with DNX](http://docs.asp.net/en/latest/dnx/console.html): We could show how to do this with aspnet-yeoman console app with the different editors? 

If we're going to do an article for each omnisharp editor, obviously there will be a large amount of overlap with the main changes being different screenshots.

Hopefully this can spur some conversation, rather than letting this stagnate for too long.

**Comment by david-driscoll** [comment]
cc @willl @Mpdreamz has anyone had any time for this yet?  Anyone able to make some time?  I might be able to in a week or two, but that's not a guarantee.

**Comment by filipw** [comment]
Closing this as outdated - read the docs is dead 😄
