### ISSUE TITLE
Omnisharp complaining about missing dependencies

### ISSUE THREAD

**Issue by polyzois** [OmniSharp/omnisharp-roslyn#337]
Hi!
This might not be an issue but I don't know where to direct a question like this.
I have tested this with both VS Code and Atom with the OmniSharp plugin. I have created a web api project using Yeoman and the aspnet generator. 
So to my problem Omnisharp thinks that my added dependencies don't exist or cant be resolved. Both the IDE:s tested can complete statements and it all runs fine using "dnx web", that is I can reach the controller and there are no errors.

I can help out with troubleshooting but would need some guidance on how to enable verbose output or trace logging or similar from the Omnisharp server.

my OS: Mac OS X Yosemite

Output from dnvm list:

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-beta4          mono                 linux/osx       
  *    1.0.0-beta8          mono                 linux/osx       default

mono --version
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Tue Oct  6 11:27:49 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

<img width="992" alt="screen shot 2015-11-16 at 09 12 20" src="https://cloud.githubusercontent.com/assets/1197628/11176976/3cd84590-8c42-11e5-8826-ee00c23d7703.png">

**Comment by david-driscoll** [comment]
Sounds like the StackExchange.Redis and FluentNHibernate dlls are not
compatible with the coreclr version of dnx.   The app runs because they do
work properly with mono, but the editor is telling you it doesn't know how
to handle those if you try to run the application on the coreclr instead of
mono.

Thanks,
David Driscoll
Microsoft MVP - OmniSharp Team

**Comment by polyzois** [comment]
Ok I see. Can I control this behaviour?  Make Omnisharp parse/run the same way/version as dnx and VS Code does?

**Comment by david-driscoll** [comment]
It's the dependencies you have defined, if they don't support coreclr those
errors will show up.

To fix it you can remove the unsupported framework from your project.json,
and they will go away.

If VSCode isn't showing the errors, I would like to see if you're project
source is available, because VSCode should have the exact same errors.

Thanks,
David Driscoll
Microsoft MVP - OmniSharp Team

**Comment by polyzois** [comment]
Ok thanks! I will investigate project.json and try and get to grips with the brave new world!
