### ISSUE TITLE
Let's investigate 'The specified runtime path 'default' does not exist' errors on OS X with VSCode

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-roslyn#347]
hi,

Can we investigate `The specified runtime path 'default' does not exist` error reported under VSCode project:
https://github.com/Microsoft/vscode/issues/126
The errors starts here:
https://github.com/OmniSharp/omnisharp-roslyn/blob/d3d8fa360cd70c7806ae52e0f318f5e76791abd0/src/OmniSharp.Dnx/DnxPaths.cs#L78

At the moment there is a situation looks like that everyone blames OmniSharp,while the promoted with docs.asp.net authoring routine for OS X does not work and the situation looks like no one cares.
I've been watching sessions under Connect() just week ago, where they were using VSCode, generator, OmniSharp on OS X (+Node + server) and then bam :imp: 

Thanks!

**Comment by phillijw** [comment]
I commented on the referenced ticket: https://github.com/Microsoft/vscode/issues/126#issuecomment-160003641

**Comment by phillijw** [comment]
Some other informations:
* It looks at the `~/.k` and the `~/.kre` folders. These are leftover from previous installations and I just deleted mine
* The main issue is that the `~/.dnx/runtimes` folder is empty. As a temp workaround I think it makes sense to symlink this folder to the `/usr/local/lib/dnx/runtimes` folder
* We need to figure out where the runtimes are _supposed_ to live because at the moment I'm still not sure

**Comment by willl** [comment]
Thanks for investigating @phillijw on jabbr. 

From my observation based on your comment and others' in issue, for some reason `Environment.GetEnvironmentVariable("DNX_HOME")` is returning _null_. Despite when doing `echo $DNX_HOME`, you're getting `/Users/username/.dnx:/usr/local/lib/dnx`.

The same is happening on my local.

Another thought, when I do a `printenv`, DNX_HOME is not listed. Thought that was weird.

So I modified my `.bash_profile` to add: `export DNX_HOME=~/.dnx`. 

Restarting my terminal, now going into the [mono C# REPL](http://www.mono-project.com/docs/tools+libraries/tools/repl/), I get `"/Users/willl/.dnx:/usr/local/lib/dnx`" rather than null for `Environment.GetEnvironmentVariable("DNX_HOME")`.

I suspect I'm not the only one getting null. 

Note: I'm not very experienced with *nix, so this is very much guess work and experimentation.

**Comment by peterblazejewicz** [comment]
Hi guys, 
Thanks!
I've managed to get it working with local installation:
https://github.com/Microsoft/vscode/issues/126#issuecomment-160200335

Can this somehow be solved? Is that `DNVM` issue or OmniSharp? The global installation is default by MS provided installer.

**Comment by david-driscoll** [comment]
My guess is that we need to add additional paths to search, does anyone have a full list of the possible ones?

This would apply across all os's, right now I see, is it the same for mac and linux?  I'm running the installer on windows to see what the location is.

Is there any source that we can reference for how the packages are created / pushed so we can figure out what the standard locations should become?  @glennc

* `/usr/local/lib/dnx` (is this where the run times live, or is there a `.dnx` folder too?)

**Comment by david-driscoll** [comment]
Here's my first stab at fixing the issue, see #354.

**Comment by ghachey** [comment]
+1 for what @david-driscoll proposes. I don't know if it is the best or even the correct way but it really should be looking in all common places and since the packages install globally by default then the symlink or reinstall in user location approaches are more work-arounds then permanent solutions.

**Comment by david-driscoll** [comment]
I've merged #354 with the latest release, would love to know if this is resolved / unresolved for anyone that's affected.

**Comment by troydai** [comment]
DNX support is retired.
