### ISSUE TITLE
Is there a plan to upgrade to dnx 1.0.0-rc1?

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-roslyn#349]
Is have plan to upgrade to dnx 1.0.0-rc1? Or just wait for 1.0.0 major release?

**Comment by willl** [comment]
@fishg Not rc1 but @troydai has an rc2 branch that he's been working on here: https://github.com/troydai/omnisharp-roslyn/tree/trdai/rc2

**Comment by kscott5** [comment]
I was going to branch this code and upgrade to 1.0.0-rc1 myself. Reviewing the project.json files it appears you have already upgrade to rc1 dependencies. However, @fishg, reviewing the global.json sdk section, you are targeting coreclr (not clr). 

Why specify coreclr when the main branch does not?  

Hence my concern.

What are the pros/cons to your approach vs what main branch is doing?

**Comment by troydai** [comment]
@kscott5 I didn't notice any other branch specify `coreclr` in `global.json` other than __my__ branch? Did you mean this branch https://github.com/troydai/omnisharp-roslyn/blob/trdai/rc2/global.json?

Well. Please ignore this one, my experiment on that branch is over. The real deal is here: https://github.com/troydai/omnisharp-roslyn/tree/trdai/cli

I'm integrating omnisharp-roslyn with the latest [.net cli](https://github.com/dotnet/cli). It will be `coreclr` only (but able to build both target frameworks).

The code under my `rc2` branch just needs minor modification to adopt `rc1` packages.

**Comment by willl** [comment]
@kscott5 I think you're a bit confused here. 

That dnx-path-rc1 branch was created by @david-driscoll purely to add additional paths to search for the dnx runtime. It's an issue people were reporting when installing ASP.NET RC 1 on OS X from http://get.asp.net as laid out in issue #347. It had nothing to do with moving omnisharp-roslyn to work run on. Until @troydai's CLI branch gets merged into master, omnisharp-roslyn has been running on beta4 due to various issues. When that happens, we'll be running on RC 2.

And it makes sense to start targeting RC 2 over RC 1 right now due to upcoming changes that are being released as part of RC 2. The most visible being `dnu`,`dnx` commands etc being moved to `dotnet` as part of the .NET CLI project.

As for your question with regards to the move to CoreCLR, it's so that we can run on the same runtime on all platforms with no other dependencies. Also, we currently need mono installed to run on OS X/Linux. Moving omnisharp-roslyn to CoreCLR means we remove that extra dependency.

**Comment by DustinCampbell** [comment]
seems like this issue is dead now that we've updated to rc2.
