### ISSUE TITLE
namespace Autocompletion/Intellisense

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#377]
_From @TheColorRed on January 13, 2016 20:30_

In C# when typing in a namespace, there is no completion hinting of namespaces that are being used.

    namespace My.Name.Space{}

When I create a new class, vscode can auto complete the `using` part, but It doesn't autocomplete the the `namespace` part.

So, when typing `namespace My.` it should suggest `Name` and anything else within the `My` space.

_Copied from original issue: Microsoft/vscode#1994_

**Comment by DustinCampbell** [comment]
Note that this is currently the same behavior as Visual Studio. Traditionally, C# IntelliSense has not functioned when declaring namespaces because, when it was originally written (15+ years ago), there wasn't a great way to keep IntelliSense from stomping all over you when you wanted to type a new identifier. We were talking about this very problem recently and I believe we decided that we should enable completion in that scenario since, these days, we have the systems in place to keep IntelliSense from misbehaving. This came up in https://github.com/dotnet/roslyn/issues/7213.

**Comment by DustinCampbell** [comment]
We've got a request to do this for C# IntelliSense that we're planning on taking: https://github.com/dotnet/roslyn/issues/7213. Once we do that work in Roslyn and expose the completion list API, OmniSharp will get this feature simply by consuming the completion list API.
