### ISSUE TITLE
omnisharp-roslyn server fails to start properly

### ISSUE THREAD

**Issue by martin-sweeney** [OmniSharp/omnisharp-roslyn#481]
When using roslyn and vim together in omnisharp the following message is shown whenever the server is started. I am using the automatic starting of the server as decribed in the installation notes on github.

/var/folders/39/w91g26n56ld31s3spxy1cwg00000gn/T/vHyf7fm/5:48: no such file or directory: /Users/jtbmanagementserviceslts/.vim/bundle/omnisharp-vim/omnisharp-roslyn/scripts/Omnisharp
--- Press ENTER to continue ---

[Steps]
- Download from github (using pathogen method)
- install vim-dispatch
- install syntastic
- install youcompleteme
- install ctrl.p
- cd ~/.vim/bundle/omnisharp-vim/omnisharp-roslyn
- run  ./build.sh
- download yeoman / yeoman aspnet generator
- run yo aspnet 
- choose 'web application'
- run  dnu restore
- run  dnu build (2242 errors here - if you use coreclr / mono compiles)
- run dnx web
- vim startup.cs - to load a c# file and vim roslyn fails in background
# Additional information:

 ./install.sh fails when you run from scripts directory in omnisharp-roslyn
# 
# python

$python -h
usage: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option]
# 
# My .vimrc

"let g:OmniSharp_server_type='v1'
let g:OmniSharp_server_type = 'roslyn'
" If you are using the omnisharp-roslyn backend, use the following
let g:syntastic_cs_checkers = ['code_checker']
# 
# dnvm settings 

$dnvm list
Active              Version Runtime Architecture OperatingSystem Alias

---

```
            1.0.0-beta4    mono                    linux/osx
      1.0.0-rc1-update1 coreclr          x64          darwin default
      1.0.0-rc1-update1    mono                    linux/osx
      1.0.0-rc1-update1 coreclr          x64          darwin default
      1.0.0-rc1-update1 coreclr          x64           linux
      1.0.0-rc1-update1    mono                    linux/osx
        1.0.0-rc2-16595 coreclr          x64          darwin
        1.0.0-rc2-16595    mono                    linux/osx
 *      1.0.0-rc2-20221 coreclr          x64          darwin
        1.0.0-rc2-20221    mono                    linux/osx
```

**Comment by david-driscoll** [comment]
Looks like the paths for vim need to be updated... not sure how best to handle that.  The build structure has changed since we've transitioned to `dotnet cli`.

The binary you want to run is something like...

for mono:
`/omnisharp-roslyn/artifacts/publish/OmniSharp/linux-x64/dnx451/OmniSharp.exe` 

for coreclr
`/omnisharp-roslyn/artifacts/publish/OmniSharp/linux-x64/dnxcore50/OmniSharp` 


I'm open to suggestions in how we could add back in `/omnisharp-roslyn/scripts/OmniSharp` such that after the build it target's the correct version for `vim` and `emacs` users.

As I'm not a linux guy I don't know what the best option would be, bash script that points to the proper version, based on current operating system to include osx users would probably work out.  Let us know what might work best for you @martin-sweeney .

**Comment by martin-sweeney** [comment]
Ok Thanks david-driscoll...

Let me think on it - I have it working manually so will look at what we can do for the script. I am new to this project so I will have to read through to find out where the script was generated.

**Comment by hal-ler** [comment]
We could generate such a short-cut as a new target in the build system based on the paths being used internally. That way users are unaffected by changes, such as tfm names and such.

**Comment by hal-ler** [comment]
Also, should the `Install` target be executed as-well, or should the shortcut use the path from the `artifacts` folder?

**Comment by hal-ler** [comment]
Any feed-back on the new script option in PR #494 is greatly appreciated.

**Comment by filipw** [comment]
this is handled by auto generating run scripts now
