### ISSUE TITLE
Incorrect and inconsistent text-editor highlighting for C# List<T> across all color themes.

### ISSUE THREAD

**Issue by lake-fall** [OmniSharp/omnisharp-roslyn#549]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add the following code to a C# class:

        public void DoSomething(List<int> list)
        {
            var newList = new List<int>();
        }

`List<int>` as a parameter has no type highlighting. 
As a variable only `int` has the correct type highlighting.
This is inconsistent with any other specified type in Visual Studio Code.
See the screenshot of Visual Studio 2015 Community for comparison.

![highlighting](https://cloud.githubusercontent.com/assets/10201888/15019068/48792790-1214-11e6-8e19-8661c4c318c8.png)

**Comment by DustinCampbell** [comment]
Thanks for reporting this problem -- much appreciated!

FWIW, This should probably be filed over in the https://github.com/OmniSharp/omnisharp-vscode repo. We already have a work item for the problem here: https://github.com/OmniSharp/omnisharp-vscode/issues/222. The situation is that VS Code uses TextMate grammars for defining syntax highlighting and doesn't yet offer an API that would allow us to provide the semantic highlights returned by OmniSharp.
