### ISSUE TITLE
Compilation Hints Get Scrambled

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#559]
_From @robbpriestley on May 22, 2016 16:47_
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.4

This has been an annoying issue ever since I started using VS Code in March. I've been living with it and don't want to complain because I love VS Code, but perhaps it will help if I report it.

Steps to Reproduce:
1. Work normally and do a minor refactor, change the signature of a method, or modify a class structure
2. The compilation hints spontaneously get all scrambled and remain that way

Sometimes clicking on the error list and selecting an "error" from the list jumps me to the source location helps to snap VS Code out of it, but most often I need to save everything and restart VS Code to fix it. Then it "re-indexes" the code and the mistaken compilation error hints go away. Executing `dotnet build` doesn't do it.

Attached is a screenshot showing a very weird one that occurred spontaneously just now.

`Type 'ServiceLogRepository' already defines a member called '.ctor' with the same parameter types [netcoreapp1.0]`

I hope I'm getting the terminology decently OK here, there are probably better names for things.

![untitled](https://cloud.githubusercontent.com/assets/16694050/15455190/f9002a1e-2001-11e6-8727-91bbad040c28.jpg)

_Copied from original issue: Microsoft/vscode#6632_

**Comment by robbpriestley** [comment]
Here's another interesting one: 

> The call is ambiguous between the following methods or properties: 'ISocialMediaRepository.Add(SocialMedia)' and 'ISocialMediaRepository.Add(SocialMedia)' [netcoreapp1.0]

**Comment by tugberkugurlu** [comment]
As stated on #567 and #566, I am seeing the same errors.

**Comment by robbpriestley** [comment]
This continues to be a really serious usability problem and in my humble opinion it should be top priority to fix. Easy for me to say, I know, but here's an example:

I'm doing a refactor today and I've quite literally needed to restart VS Code a dozen times in order to clear the scrambled compilation hints. Now members of my team are reporting it as a distraction as well. It's more than just annoying, it leads to incorrect conversations between team members as well, and is a productivity hit.

**Comment by robbpriestley** [comment]
Don't get me wrong, I am a huge fan of VS Code and I'm sorry to be critical, but it baffles me that so many features I never use keep getting added to the product while this major fundamental usability issue continues to plague it.

I find myself needing to shut down and re-open VS Code on a regular basis to help it correct itself of faulty compiler issues and errors, and it affects my basic productivity. 👎

**Comment by DustinCampbell** [comment]
Hey guys --- sorry I hadn't noticed this C# for VS Code issue. I'll migrate it over to the omnisharp-vscode repo where it belongs.

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1450

**Comment by unhammer** [comment]
I believe this is an issue here, not (just) in the vscode part, at least for v1.32.6 and v1.32.8. As https://github.com/OmniSharp/omnisharp-vscode/issues/1450#issuecomment-432516876 says, it happens when using omnisharp from Emacs.

(Downgrading omnisharp-roslyn to 1.32.0 solved this issue for me on Emacs 26.1 with omnisharp-emacs 20181206.21 from melpa, dotnet 2.2.102 on Ubuntu 18.04.)
