### ISSUE TITLE
C# Resolve for usings

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#572]
_From @Bungalow12 on June 1, 2016 23:56_
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.4

Steps to Reproduce: 
1. Type in a class that exists somewhere in a referenced library. 
2. Right click the class
3. Go to Resolve -> then Add using statement or replace with full namespace

This is a feature I love in Visual Studio and MonoDevelop. However I'm really enjoying vscode and would like this to be my main editor. This is a feature I adored.

_Copied from original issue: Microsoft/vscode#7110_

**Comment by razzmatazz** [comment]
I think fixusings commands does this, except it does not do "replace with full namespace"..

**Comment by MozJon** [comment]
How do you use /fixusings? Is it a command line option? I'm looking for it in the editor. Perhaps there is a place to enter this command I'm unfamiliar with.

**Comment by razzmatazz** [comment]
@MozJon – thats internal API for omnisharp-roslyn and depends on how particular editor integration package has that provided for the user. On emacs it is `omnisharp-fix-usings` (for the 'master' branch). Not sure about VSCode..

**Comment by Bungalow12** [comment]
So is this something VSCode needs to implement or something for the OmniSharp plugin?

**Comment by nathanielcook** [comment]
Closely related: I notice that the quick fix menu keyboard shortcut in Visual Studio Code suggests adding a using statement...but _only if there is a period after the symbol_. For example, if I type `File` and get a squiggly because there is not yet a `using System.IO;` at the top, if I launch quick fix using the keyboard shortcut it offers to fully qualify `File` as `System.IO.File`, but does _not_ offer to add the using statement. If however I type `File.`, move my cursor to be between the `e` and the `.`, and then try the quick fix keyboard shortcut again, this time it offers to add the using statement. This seems like a bug that could be fixed fairly easily. Does anyone know anything about that by chance?

And yes, I agree with the opening poster; a right click on the symbol should also offer to add the using statement like the quick fix menu (normally) does.

**Comment by filipw** [comment]
This has been implemented as auto-import.
Set `enableImportCompletion: true` to enable it https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#roslyn-extensions-options
