### ISSUE TITLE
Intellisense comments tooltip does not support Chinese character display

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#573]
_From @lishali12345 on June 2, 2016 7:8_

- VSCode Version:Version 1.1.1 (1.1.1)
- OS Version: OSX EI Capitan Version 10.11.5

Steps to Reproduce:

1. 
![Chinese character display correctly in editor](https://cloud.githubusercontent.com/assets/170981/15736555/235527fe-28d3-11e6-8497-e9bb255c509c.png)

2. 
![Chinese character display not correctly in tooltip](https://cloud.githubusercontent.com/assets/170981/15736618/7c870216-28d3-11e6-8589-b3a4ce694667.jpg)

The Chinese character in the second screen shot display like "??????". Please let me know If I can do any config to make this right, thanks a lot.

_Copied from original issue: Microsoft/vscode#7120_

**Comment by jrieken** [comment]
_From @joaomoreno on June 2, 2016 7:57_

@jrieken This is hover. And clearly the div in the hover is able to render chinese characters. Shouldn't this be forwarded to the csharp guys?

**Comment by jrieken** [comment]
I see. Thanks

**Comment by DustinCampbell** [comment]
I'm betting this will be addressed by https://github.com/OmniSharp/omnisharp-roslyn/pull/598.

**Comment by lishali12345** [comment]
I'm here just want to make something clear. When  I upgrade the Visual Studio Code to v1.3.1 and C# extension to v1.3.0, then the Chinese characters show in intellisense comments very well, just like the pic:
 
![qq20160805-0](https://cloud.githubusercontent.com/assets/170981/17432154/4d0ec548-5b30-11e6-8664-ee070685222d.png)

But when I just upgrade the Visual Studio Code to v1.4.0 release in July, the problem comes back again. So I roll back the Code to v1.3.1 to make me feel better with Chinese characters comments.

Thanks.

**Comment by DustinCampbell** [comment]
This issue really should be on the https://github.com/OmniSharp/omnisharp-vscode repo. However, this is now fixed for the next release of the C# Extension for VS Code. The latest beta with this change is available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.4.0-beta9).
