### ISSUE TITLE
Installing on Fedora 23

### ISSUE THREAD

**Issue by victor-borges** [OmniSharp/omnisharp-roslyn#577]
I've already installed the [dotnet cli for centos](https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-preview1-002702/dotnet-dev-centos-x64.1.0.0-preview1-002702.tar.gz) on fedora 23, but when i tried to install the omnisharp-roslyn, it forced the download of an inexistent version for fedora and failed while executing the task `BuildEnvironment`, throwing the message: 

> _dotnet_install: Error: OS name could not be detected_
> dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-preview1-002702/dotnet-dev--x64.1.0.0-preview1-002702.tar.gz

How can I change this URL for the one used on centos version?

---

dotnet's version installed : "1.0.0-preview1-002702"

**Comment by willl** [comment]
Hi Victor, are you using VS Code? Or another editor?

I assume that download url is coming from your editor, right? If you're using VS Code, then you should report this as an issue here: https://github.com/OmniSharp/omnisharp-vscode

Otherwise, I would suggest downloading the CentOS build directly from the releases page: https://github.com/OmniSharp/omnisharp-roslyn/releases

And then following the instructions in the read me https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/README.md#vs-code

**Comment by victor-borges** [comment]
thank you @will, and sorry for the late answer.

**Comment by will** [comment]
Glad I could help
