### ISSUE TITLE
build error on Restore; macOS Sierra

### ISSUE THREAD

**Issue by jonbash** [OmniSharp/omnisharp-roslyn#668]
This is the result upon running build.sh on the dev branch on the latest version of macOS with the latest version of Mono installed: [http://pastebin.com/L5Tj5m7m](http://pastebin.com/L5Tj5m7m)

Let me know if you need anything else. Thanks!

**Comment by willl** [comment]
Looking at the error, I suspect the issue is related to not having OpenSSL installed correctly.

If this is the case, go [here](https://www.microsoft.com/net/core#macos) and follow the steps outlined in the pre-reqs section. If that still fails, then try the instructions here: https://github.com/dotnet/core/blob/master/cli/known-issues.md#openssl-dependency-on-os-x

**Comment by rthompsonj** [comment]
can confirm that symlinking the two library files from openssl gets past the error in the "Restore" portion.

```
> brew install openssl
> ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
> ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

**Comment by DustinCampbell** [comment]
It seems like this isn't an issue anymore, correct? I'm going to optimistically close, but let us know if this is still a problem for you.
