### ISSUE TITLE
Properly order Code Actions

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#758]
Today, code actions are ordered with some [very suspicious logic](https://github.com/OmniSharp/omnisharp-roslyn/blob/v1.9-beta25/src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs#L75-L76).

Roslyn defines an [ExtensionOrderAttribute](https://github.com/dotnet/roslyn/blob/version-2.0.0-rc3/src/Workspaces/Core/Portable/ExtensionOrderAttribute.cs) that is applied to code fixes to allow them to state their order dependencies. OmniSharp should use this to create a sensible order.

**Comment by david-driscoll** [comment]
... hey the `.Reverse()` usually orders them in alphabetical order... 👍

**Comment by DustinCampbell** [comment]
:smile:

**Comment by filipw** [comment]
would be great if [this](https://github.com/dotnet/roslyn/blob/version-2.0.0/src/Workspaces/Core/Portable/Shared/Utilities/ExtensionOrderer.cs) was public

**Comment by DustinCampbell** [comment]
Yeah, I know. It's a bit silly.

**Comment by akshita31** [comment]
This issue has been fixed in the 1.14 milestone. We just released a beta of 1.14 - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta4. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install a beta release of C# for VS Code.
