### ISSUE TITLE
Changing file extensions OmniSharp looks for

### ISSUE THREAD

**Issue by GaZaTu** [OmniSharp/omnisharp-roslyn#810]
Hi,
I tried to build omnisharp-roslyn so that it looks for different file extensions.
  from `".cs"` to `".vala", "vapi"`
But this way no files work anymore, neither .cs nor .vala.
Now my question is, is it even possible to change that?

In the files `DotNetProjectSystem.cs` and `MSBuildProjectSystem.cs` I changed this:
`public IEnumerable<string> Extensions { get; } = new string[] { ".cs" };`
to this:
`public IEnumerable<string> Extensions { get; } = new string[] { ".vala", ".vapi" };`

Not a real issue i know. ;)

**Comment by DustinCampbell** [comment]
OmniSharp doesn't really look for file extensions other than project files. The project systems load files when processing their appropriate project file -- e.g. DotNetProjectSystem processes project.json and MSBuildProjectSystem processes .csproj.

**Comment by GaZaTu** [comment]
So I have to build roslyn myself to change this behavior?

**Comment by filipw** [comment]
@DustinCampbell maybe we could add the ability to define your own extensions through the `omnisharp.json` file?
it would make sense in some edge cases, i.e. if you want to forcibly light up omnisharp for `*.cake` files or if you have your own C#-based DSL files. it would probably not be the great experience since project systems are very specialized and need to know exactly what they are doing, but it might make sense to leave this as an opt-in?

**Comment by DustinCampbell** [comment]
@GaZaTu: No, I did not mean that you would rebuild Roslyn, which is the C# compiler itself. My point is that the project systems for project.json and .csproj are deeply ingrained with the notion of C#, so they only pick of .cs files. Getting them to do otherwise would be challenging.

@filipw: Possibly. In the case of .vala, this is C#-ish, but it's really not C# and has a different type system. If the goal is to get C# IntelliSense, it's going to be pretty bad as soon as you start using specialized vala keywords and types.

WRT Cake, that's much closer to C# than Vala, since it's just C# scripting variants. However, the trick with Cake is adding the special handling for binding their DSL. @david-driscoll was talking about this at one point.

**Comment by GaZaTu** [comment]
:/

**Comment by DustinCampbell** [comment]
Sorry @GaZaTu. There's just not an _easy_ solution.
