### ISSUE TITLE
Question: Importing namespaces from another CSX file

### ISSUE THREAD

**Issue by tpodolak** [OmniSharp/omnisharp-roslyn#811]
I've just updated omnisharp-roslyn to the newest version and it seems there were some breaking changes when it comes to csx files support (in this version or in previous ones). Previously I was able to import all of my namespaces in one file 
````
#r "System.Web"

using System.Web.Caching;
...
...
...
````
and later on reference this file in another CSX files
````
#load "./imports.csx"
var cache = new Cache();
````
so that I had intellisense support without polluting other csx files with namespace imports. Unfortunately, this feature seems to be gone now. Is there any way to restore this behavior? This feature was very helpful for writing cake build scripts (I was using some custom made assemblies to provide partial intellisense for cake build scripts)
/cc @filipw

**Comment by filipw** [comment]
That's a good observation, but this is indeed by design. 

It used to work in the older versions of OmniSharp as it was using the manual pre-processing of files and [scriptcs](https://github.com/scriptcs/scriptcs) style of file parsing and script context set up. However, we switched to standard C# Interactive CSX support a while ago.

In standard Roslyn-based C# scripting, using statements are only scoped to the file in which they are defined and do not propagate to other files via `#load` directive. There is an open feature request regarding just that in the Roslyn repo https://github.com/dotnet/roslyn/issues/13889. Once that is available in Roslyn it will light up in OmniSharp too.

**Comment by tpodolak** [comment]
Thanks for clarification
