### ISSUE TITLE
Merge OmniSharp.Host.csproj into OmniSharp.csproj?

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#860]
It's not clear to me why OmniSharp.Host.csproj exists. :smile:

cc @david-driscoll

**Comment by david-driscoll** [comment]
Is "because" a valid answer?

It was born out of a desire to separate responsibilities, where Host could be used by multiple sources too bootstrap the application.  It was however still tied to Asp.Net Core and middleware.   I always envisioned an idealized world where we had something like Http, Stdio, and even mayber WebSocket support.

**Comment by DustinCampbell** [comment]
That makes sense. OmniSharp.Host.csproj could become the public API surface area for hosting OmniSharp via some communication mechanism. I like that idea quite a bit.
