### ISSUE TITLE
Omnisharp doesn't respect InternalsVisibleTo

### ISSUE THREAD

**Issue by TyOverby** [OmniSharp/omnisharp-roslyn#886]
When I attempt to load a bunch of projects from vscode I get errors everywhere for inaccessibility due to protection level.  These projects build just fine on the command line, and load in VS without issue.

**Comment by DustinCampbell** [comment]
@TyOverby: OmniSharp should support InternalsVisibleTo just fine. Is it possible that the project you're loading is Roslyn? In Roslyn, the InternalsVisibleTo attributes are generated via MSBuild tasks, which OmniSharp won't run today.

**Comment by TyOverby** [comment]
@DustinCampbell Ah, that'd be the issue then!  Is there any workaround?

**Comment by DustinCampbell** [comment]
Not yet, the problem is that OmniSharp needs to run the "Compile" target as a design-time build. Today, it just runs the ResolveAssemblyReferences target. I tried switching it, but ran into some complexities, so it'll take a bit more effort.

I'm looking into this as part of https://github.com/OmniSharp/omnisharp-vscode/issues/1531.
