### ISSUE TITLE
Completion hard selects a partial match item

### ISSUE THREAD

**Issue by balajikris** [OmniSharp/omnisharp-roslyn#910]
**C# Extension version:  1.11.0
VS Code version: 1.13.1**

In this case, when I type `<` after `IList`, completion hard selects **I**nterval**List**Extensions, whereas, I'd like to type out `IList<int>` and invoke add using later to resolve the type.

![image](https://user-images.githubusercontent.com/4213867/28181566-f5233404-67bd-11e7-92ec-687a99dd26db.png)

/cc: @DustinCampbell

**Comment by DustinCampbell** [comment]
There's no such thing as hard vs. soft selection in VS Code. This would have the same behavior in VS.

**Comment by balajikris** [comment]
Oh, I see. l _feel_ completing a partial match is a bit too strong (and unhelpful in this case).

**Comment by DustinCampbell** [comment]
That's how Visual Studio works though, and it would significantly break muscle memory to do otherwise. Eventually, when we have the ability to show completion items that aren't in referenced assemblies or using directives, this will work better for you. In VS, the answer is "suggestion mode" using <kbd>Ctrl+Alt+Space</kbd>. In VS Code, there isn't a good answer.

**Comment by DustinCampbell** [comment]
Also, I assume you meant to file this in omnisharp-vscode? :smile:

**Comment by balajikris** [comment]
ah yes - you're right. :-)
